// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelRun() {
  return window['go']['main']['App']['CancelRun']();
}

export function CheckAllLoginStatus() {
  return window['go']['main']['App']['CheckAllLoginStatus']();
}

export function CheckLoginStatus(arg1) {
  return window['go']['main']['App']['CheckLoginStatus'](arg1);
}

export function ClearLogs() {
  return window['go']['main']['App']['ClearLogs']();
}

export function CreateSchedule(arg1) {
  return window['go']['main']['App']['CreateSchedule'](arg1);
}

export function DeleteAutomation(arg1, arg2) {
  return window['go']['main']['App']['DeleteAutomation'](arg1, arg2);
}

export function DeleteSchedule(arg1) {
  return window['go']['main']['App']['DeleteSchedule'](arg1);
}

export function ExportLogs() {
  return window['go']['main']['App']['ExportLogs']();
}

export function GetAutomations(arg1) {
  return window['go']['main']['App']['GetAutomations'](arg1);
}

export function GetBrowserConfig() {
  return window['go']['main']['App']['GetBrowserConfig']();
}

export function GetBrowserStatus() {
  return window['go']['main']['App']['GetBrowserStatus']();
}

export function GetLogs() {
  return window['go']['main']['App']['GetLogs']();
}

export function GetPlatforms() {
  return window['go']['main']['App']['GetPlatforms']();
}

export function GetScheduleStats(arg1) {
  return window['go']['main']['App']['GetScheduleStats'](arg1);
}

export function GetSchedules() {
  return window['go']['main']['App']['GetSchedules']();
}

export function ImportCookies(arg1, arg2) {
  return window['go']['main']['App']['ImportCookies'](arg1, arg2);
}

export function ImportRecording(arg1, arg2) {
  return window['go']['main']['App']['ImportRecording'](arg1, arg2);
}

export function LogFromFrontend(arg1, arg2, arg3) {
  return window['go']['main']['App']['LogFromFrontend'](arg1, arg2, arg3);
}

export function OpenPlatform(arg1) {
  return window['go']['main']['App']['OpenPlatform'](arg1);
}

export function PauseSchedule(arg1) {
  return window['go']['main']['App']['PauseSchedule'](arg1);
}

export function PurgeSession(arg1) {
  return window['go']['main']['App']['PurgeSession'](arg1);
}

export function ResetBrowserConfig() {
  return window['go']['main']['App']['ResetBrowserConfig']();
}

export function RestartBrowser() {
  return window['go']['main']['App']['RestartBrowser']();
}

export function ResumeSchedule(arg1) {
  return window['go']['main']['App']['ResumeSchedule'](arg1);
}

export function RunAutomation(arg1, arg2) {
  return window['go']['main']['App']['RunAutomation'](arg1, arg2);
}

export function SaveAutomation(arg1, arg2) {
  return window['go']['main']['App']['SaveAutomation'](arg1, arg2);
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}

export function StartBrowser() {
  return window['go']['main']['App']['StartBrowser']();
}

export function StopBrowser() {
  return window['go']['main']['App']['StopBrowser']();
}

export function TestAutomation(arg1, arg2) {
  return window['go']['main']['App']['TestAutomation'](arg1, arg2);
}

export function TriggerUpload(arg1) {
  return window['go']['main']['App']['TriggerUpload'](arg1);
}

export function UpdateBrowserConfig(arg1) {
  return window['go']['main']['App']['UpdateBrowserConfig'](arg1);
}

export function UpdateSchedule(arg1, arg2) {
  return window['go']['main']['App']['UpdateSchedule'](arg1, arg2);
}
