// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {workflow} from '../models';

export function CheckAllLoginStatus():Promise<Array<main.PlatformResponse>>;

export function CheckLoginStatus(arg1:string):Promise<main.PlatformResponse>;

export function ClearLogs():Promise<void>;

export function CreateSchedule(arg1:main.CreateScheduleRequest):Promise<main.ScheduleResponse>;

export function DeleteSchedule(arg1:string):Promise<boolean>;

export function ExportLogs():Promise<string>;

export function GetBrowserConfig():Promise<main.BrowserConfigResponse>;

export function GetBrowserStatus():Promise<main.BrowserStatusResponse>;

export function GetLogs():Promise<Array<main.LogEntryResponse>>;

export function GetPlatforms():Promise<Array<main.PlatformResponse>>;

export function GetScheduleStats(arg1:string):Promise<main.ScheduleResponse>;

export function GetSchedules():Promise<Array<main.ScheduleResponse>>;

export function ImportCookies(arg1:string,arg2:string):Promise<main.PlatformResponse>;

export function OpenPlatform(arg1:string):Promise<main.BrowserStatusResponse>;

export function PauseSchedule(arg1:string):Promise<main.ScheduleResponse>;

export function PurgeSession(arg1:string):Promise<main.PlatformResponse>;

export function ResetBrowserConfig():Promise<main.BrowserConfigResponse>;

export function RestartBrowser():Promise<main.BrowserStatusResponse>;

export function ResumeSchedule(arg1:string):Promise<main.ScheduleResponse>;

export function StartBrowser():Promise<main.BrowserStatusResponse>;

export function StopBrowser():Promise<main.BrowserStatusResponse>;

export function TriggerUpload(arg1:workflow.UploadRequest):Promise<main.UploadResponse>;

export function UpdateBrowserConfig(arg1:main.BrowserConfigResponse):Promise<main.BrowserConfigResponse>;

export function UpdateSchedule(arg1:string,arg2:main.CreateScheduleRequest):Promise<main.ScheduleResponse>;
